// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVztvIIqYqGiDIPgFFIMhYsTpy_ZULqss',
    appId: '1:173409243741:web:1425976a5a8284f070f3b4',
    messagingSenderId: '173409243741',
    projectId: 'mobile-billing-app-14875',
    authDomain: 'mobile-billing-app-14875.firebaseapp.com',
    storageBucket: 'mobile-billing-app-14875.firebasestorage.app',
    measurementId: 'G-QBGX9P8N5C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo5OwnOmMJYOxiem3mOEDutfFmci3OTE0',
    appId: '1:173409243741:android:cd7f3b6e8d5d98ac70f3b4',
    messagingSenderId: '173409243741',
    projectId: 'mobile-billing-app-14875',
    storageBucket: 'mobile-billing-app-14875.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0XpOD8MHSp3mnJz-D6xkssq698tJ6f_w',
    appId: '1:173409243741:ios:f28df3400476fa2370f3b4',
    messagingSenderId: '173409243741',
    projectId: 'mobile-billing-app-14875',
    storageBucket: 'mobile-billing-app-14875.firebasestorage.app',
    iosBundleId: 'com.example.billingApp',
  );

}